repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: [--autofix, --indent, '2']
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.1.3
  hooks:
  - id: pretty-format-rust
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-ini
    args: [--autofix]
    files: ^.+\.(cfg|ini|toml)$
